// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://qhrrdahejgsltmihsgpy.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFocnJkYWhlamdzbHRtaWhzZ3B5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4NjU5NTQsImV4cCI6MjA4ODQ0MTk1NH0.Xps4uo2SWfx9ZnTVLt26ShtCJeStrGaz8THQgaui5Q0';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});